# Generated by Django 3.0.3 on 2020-08-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('data_label', models.CharField(max_length=20)),
                ('data_value', models.IntegerField(default=0)),
            ],
        ),
    ]
