  version: '3'

  services:
    api:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      restart: unless-stopped
      volumes:
        - .:/code
      ports:
        - "8000:8000"
    nginx:
      image: nginx:1.17-alpine
      depends_on:
        - api
      links:
        - api
      restart: unless-stopped
      volumes:
        - ./data/nginx:/etc/nginx/conf.d
        - ./data/cert:/etc/cert
      ports:
        - "80:80"
        - "443:443"
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
