# Generated by Django 3.0.3 on 2020-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data',
            field=models.FloatField(),
        ),
    ]
