# Generated by Django 3.0.3 on 2020-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
