# Generated by Django 3.0.3 on 2020-08-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_jwt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
